### ISSUE TITLE
Package name

### ISSUE THREAD

**Issue by phase** [chibill/DeObfuscating-Loader#1]
For CraftDevs/CraftClient, I put the code in the package `craftdevs.phase.craftclient`, and I think you should put yours in `craftdevs.chibill.deobfloader`.

**Comment by wgaylord** [comment]
okay I will do when I get the chance. (This issue did not really even come up on my email...)

**Comment by wgaylord** [comment]
Fix with 33b7ee64 and https://github.com/CraftDevs/DeobfCraft/commit/1025c3caa006dcaa801a1438e92b5fce0c0a0a46
